name: CI

on:
  pull_request:
  release:
    types: [released]
  schedule:
    # runs every two hours
    - cron: '0 */8 * * *'

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.10.x'
          cache: 'yarn'
      - run: yarn install --immutable
      - run: yarn run format-check

  es-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.10.x'
          cache: 'yarn'
      - run: yarn install --immutable
      - run: yarn run lint-check

  init:
    runs-on: ubuntu-latest
    env:
      ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
      INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      WALLET_ADDRESS: ${{ secrets.WALLET_ADDRESS }}
      SECOND_PRIVATE_KEY: ${{ secrets.SECOND_PRIVATE_KEY }}
      SECOND_WALLET_ADDRESS: ${{ secrets.SECOND_WALLET_ADDRESS }}
      THIRD_PRIVATE_KEY: ${{ secrets.THIRD_PRIVATE_KEY }}
      THIRD_WALLET_ADDRESS: ${{ secrets.THIRD_WALLET_ADDRESS }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.10.x'
          cache: 'yarn'
      - run: yarn install --immutable
      - run: yarn start

  tests:
    runs-on: ubuntu-latest
    env:
      ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
      INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      WALLET_ADDRESS: ${{ secrets.WALLET_ADDRESS }}
      SECOND_PRIVATE_KEY: ${{ secrets.SECOND_PRIVATE_KEY }}
      SECOND_WALLET_ADDRESS: ${{ secrets.SECOND_WALLET_ADDRESS }}
      THIRD_PRIVATE_KEY: ${{ secrets.THIRD_PRIVATE_KEY }}
      THIRD_WALLET_ADDRESS: ${{ secrets.THIRD_WALLET_ADDRESS }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.10.x'
          cache: 'yarn'
      - run: yarn install --immutable
      - run: yarn test
